# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- id: server
  dir: server
  binary: server
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
- id: worker
  dir: worker
  binary: worker
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - artifacts: checksum
release:
  draft: true
  prerelease: true
  disable: true